### ISSUE TITLE
Pilot Failure but job is submitting to BW

### ISSUE THREAD

**Issue by FranklinBetten** [radical-collaboration/extasy-bpti#12]
The latest runmy.py submits to BW and starts to run but the pilot fails. Here is the output from my run. 

```
(myenv) hal9000@js-17-8:~/Documents/feature_entk-0.7/bw_sync_01/bw_p14b02_left_d3_k12_1000_k34_1000_1ns_sims_02$ python runme.py --Kconfig gmxcoco.wcfg --RPconfig bluewaters.rcfg
EnTK session: re.session.js-17-8.jetstream-cloud.org.hal9000.017843.0003
Creating AppManager                                                           ok
Validating and assigning resource manager                                     ok
iter_cnt =  0
s5.name grompp-stage-0
s6.name =  mdrun-stage-0
s7.name =  traj-stage-0
s8.name =  trajconv-stage-0
s9.name =  coco-iter-0
Setting up RabbitMQ system                                                    ok
2018-11-07 21:20:29,540: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has completed
^C^C2018-11-07 22:00:55,146: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Execution interrupted by user (you probably hit Ctrl+C), trying to cancel enqueuer thread gracefully...
Traceback (most recent call last):
  File "runme.py", line 640, in <module>
    appman.run()
  File "/home/hal9000/Documents/feature_entk-0.7/myenv/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 475, in run
    raise KeyboardInterrupt
KeyboardInterrupt
(myenv) hal9000@js-17-8:~/Documents/feature_entk-0.7/bw_sync_01/bw_p14b02_left_d3_k12_1000_k34_1000_1ns_sims_02$

```

On bluewaters the job seems to immediately cancel

```

bettenco@h2ologin3:~> qstat -u bettenco

bwsched.ncsa.illinois.edu: Blue_Waters
                                                                                  Req'd       Req'd       Elap
Job ID                  Username    Queue    Jobname          SessID  NDS   TSK   Memory      Time    S   Time
----------------------- ----------- -------- ---------------- ------ ----- ------ --------- --------- - ---------
9191390.bw              bettenco    high     pilot.0000        20032     5    160       --   00:30:00 C       --

```

I had to change the runme.py script a bit to get it to submit to bluewaters.

it was
```
hostname = os.environ.get('RMQ_HOSTNAME', 'localhost')
port = int(os.environ.get('RMQ_PORT', 5672))
```
but that configuration for RabbitMQ didnt work so I changed it to the values listed in the instructions
```

hostname = os.environ.get('RMQ_HOSTNAME', 'two.radical-project.org')#'localhost')
port = int(os.environ.get('RMQ_PORT', 33211))#5672))

```

**Comment by vivek-bala** [comment]
Yes, that's correct and as per the instructions at https://github.com/radical-collaboration/extasy-bpti/blob/feature/entk-0.7/gmxcoco-bpti/instructions.md.

Can you verify that you recreated the virtualenv on Blue Waters as per the instructions in the above document?

**Comment by FranklinBetten** [comment]
My VM stack was 

```

**Comment by FranklinBetten** [comment]
Thanks Vivek that solved it! 

My VM stack is 
```
hal9000@js-17-8:~/Documents/feature_entk-0.7$ source myenv/bin/activate
(myenv) hal9000@js-17-8:~/Documents/feature_entk-0.7$ radical-stack 

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/hal9000/Documents/feature_entk-0.7/myenv

  radical.entk         : 0.7.6
  radical.pilot        : 0.50.11-v0.50.11@devel
  radical.utils        : 0.50.2
  saga                 : 0.50.0

```

So on BW I ran the following to set up the new ve

```
bettenco@h2ologin1:~/scratch/radical.pilot.sandbox> wget https://raw.githubusercontent.com/radical-cybertools/radical.pilot/devel/bin/radical-pilot-create-static-ve
bettenco@h2ologin1:~/scratch/radical.pilot.sandbox> sh ./radical-pilot-create-static-ve ve.ncsa.bw_aprun.0.50.11 bw

script : ./radical-pilot-create-static-ve
prefix : ve.ncsa.bw_aprun.0.50.11
arg    : bw

invoke BW magic

script : ./radical-pilot-create-static-ve
prefix : /u/sciteam/bettenco/scratch/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.50.11
arg    : bwpy

create bwpy ve [/u/sciteam/bettenco/scratch/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.50.11]
install virtualenv ......
create  virtualenv ....
update  setuptools ..............
update  pip .................................................
install pymongo==2.8 ...
install python-hostlist ...
install netifaces==0.10.4 ...
install setproctitle ...
install ntplib ...
install pyzmq ....
install apache-libcloud ..............
install colorama ....
install backports.ssl-match-hostname ......
install msgpack-python ......
install future ......
fix bwpy ve
wrap   python
wrap   python2
patch  python2.7

---------------------------------------------------------------------

PYTHONPATH: /opt/xalt/0.7.6/sles11.3/libexec
Python 2.7.14
python: /u/sciteam/bettenco/scratch/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.50.11/bin/python ()

---------------------------------------------------------------------

```

We are Up and Running now!
