### ISSUE TITLE
RP failing halfway through cycle

### ISSUE THREAD

**Issue by ChrisSuess** [radical-collaboration/extasy-bpti#18]
So I have managed to get RP runnning on BW everything seemed to be working until it gets stage 3 in the workflow and then i get the following error:

```
2019-02-06 11:39:34,315: radical.entk.task_manager.0000: task-manager                    : Thread-1       : ERROR   : Transition of task.0040 to SUBMITTING state failed, error: (-1, "error(104, 'Connection reset by peer')")
Traceback (most recent call last):
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/radical/entk/utils/init_transition.py", line 27, in transition
    local_prof=profiler)
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/radical/entk/utils/sync_initiator.py", line 24, in sync_with_master
    properties=pika.BasicProperties(correlation_id=corr_id)
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2120, in basic_publish
    mandatory, immediate)
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2207, in publish
    self._flush_output()
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 477, in _flush_output
    result.reason_text)
ConnectionClosed: (-1, "error(104, 'Connection reset by peer')")
Traceback (most recent call last):
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/radical/entk/execman/rp/task_manager.py", line 303, in _process_tasks
    logger=logger)
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/radical/entk/utils/init_transition.py", line 34, in transition
    obj.state = old_state
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/radical/entk/task/task.py", line 450, in state
    raise TypeError(expected_type=str, actual_type=type(val))
NameError: global name 'val' is not defined

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/radical/entk/execman/rp/task_manager.py", line 323, in _process_tasks
    raise EnTKError(ex)
EnTKError: global name 'val' is not defined
```

After this it schedules the next jobs but seems to hang and just gives the following heart beat message:

```
2019-02-06 12:29:33,406: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : flush: [  159] [     ] (flush pty read cache)
2019-02-06 12:29:33,508: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : write: [  159] [  161] (unset GREP_OPTIONS; /opt/torque/6.0.4/bin/qstat -f1 9589509 | grep -E -i '(job_state)|(Job_Name)|(exec_host)|(exit_status)|(ctime)|(start_time)|(stime)|(mtime)'\n)
2019-02-06 12:29:33,623: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  159] [   27] (    Job_Name = pilot.0000\n)
2019-02-06 12:29:33,624: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  159] [  210] (    job_state = R\n    ctime = Wed Feb  6 05:30:22 2019\n    exec_host = 11720/0-31+11721/0-31+11722/0-31+11723/0-31+11724/0-31\n    mtime = Wed Feb  6 05:31:39 2019\n    start_time = Wed Feb  6 05:31:39 2019\n)
2019-02-06 12:29:33,625: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  159] [   10] (PROMPT-0->)
2019-02-06 12:29:33,625: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : INFO    : Job monitoring thread updating Job [torque+gsissh://bw.ncsa.illinois.edu]-[9589509] (old state: Running, new state: Running)
2019-02-06 12:29:39,814: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Received heartbeat response
2019-02-06 12:29:39,820: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
2019-02-06 12:29:39,882: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Received heartbeat request
2019-02-06 12:29:39,883: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Sent heartbeat response
2019-02-06 12:30:09,852: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Received heartbeat response
2019-02-06 12:30:09,862: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
2019-02-06 12:30:09,941: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Received heartbeat request
2019-02-06 12:30:09,941: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Sent heartbeat response
2019-02-06 12:30:33,684: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : flush: [  159] [     ] (flush pty read cache)
2019-02-06 12:30:33,785: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : write: [  159] [  161] (unset GREP_OPTIONS; /opt/torque/6.0.4/bin/qstat -f1 9589509 | grep -E -i '(job_state)|(Job_Name)|(exec_host)|(exit_status)|(ctime)|(start_time)|(stime)|(mtime)'\n)
2019-02-06 12:30:33,924: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  159] [   27] (    Job_Name = pilot.0000\n)
2019-02-06 12:30:33,926: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  159] [  220] (    job_state = R\n    ctime = Wed Feb  6 05:30:22 2019\n    exec_host = 11720/0-31+11721/0-31+11722/0-31+11723/0-31+11724/0-31\n    mtime = Wed Feb  6 05:31:39 2019\n    start_time = Wed Feb  6 05:31:39 2019\nPROMPT-0->)
```

**Comment by vivek-bala** [comment]
Great that you got running on BW! Can you point me the exact script that you are running? just want to make sure we are looking at the same script. I can take a look at stage 3.

**Comment by ChrisSuess** [comment]
its the `runme.py` on the `feature/entk0.7` branch using the following command

```
python runme.py --RPconfig bluewaters.rcfg --Kconfig gmxcoco.wcfg
```

**Comment by vivek-bala** [comment]
Thanks Chris. The script as such looks correct. Would you have the entire message that is printed to standard output? If you have any log files please do attach it as well.

If not, could you run it again with a few environment variables:
```
export RADICAL_ENTK_VERBOSE=INFO
export RADICAL_PILOT_VERBOSE=DEBUG
python runme.py --RPconfig bluewaters.rcfg --Kconfig gmxcoco.wcfg | tee output.log
<wait to finish or crash>
radical-pilot-fetch-logfiles <session id the run re.session.*> (a folder starting with re.session would have been created already)
```
You can then attach output.log and the re.session.* folder. That should have everything required to debug the issue.

**Comment by ChrisSuess** [comment]
Thanks, ill give this a go!

In the meantime, all the relevant files created by RP are located on BW at:

```
/u/sciteam/suess/scratch/radical.pilot.sandbox/re.session.ip-172-31-39-107.ubuntu.017933.0004
```

I thought sending you a link to the source of my logs maybe more helpful!

Have you been able to successfully run a job on BW using the above command from the example folder? This may help narrow down the source of the problem.

**Comment by ChrisSuess** [comment]
heres the BW error log

[BW_Errors.log](https://github.com/radical-collaboration/extasy-bpti/files/2845482/BW_Errors.log)

**Comment by ChrisSuess** [comment]
output log from `python runme.py --RPconfig bluewaters.rcfg --Kconfig gmxcoco.wcfg | tee output.log`

[output.log](https://github.com/radical-collaboration/extasy-bpti/files/2845489/output.log)

**Comment by vivek-bala** [comment]
Thanks! Looking at the logs, it does look like a connection error. I'm giving it a try as well, I'll keep you posted if I can also confirm that it is a connection problem.

**Comment by vivek-bala** [comment]
I was able to reproduce this issue. Debugging ongoing.

**Comment by vivek-bala** [comment]
Just an update. I was able to locate the bug. You should be able to run it with 10 CUs ([this](https://github.com/radical-collaboration/extasy-bpti/blob/feature/entk-0.7/gmxcoco-bpti/gmxcoco.wcfg#L8) line) if you wanted to test the entire workflow for a small case. 

I should be able to resolve the bug by end of day today.

**Comment by ChrisSuess** [comment]
Good news, will it only work with 10 CUs at the moment?

**Comment by ChrisSuess** [comment]
> Just an update. I was able to locate the bug. You should be able to run it with 10 CUs ([this](https://github.com/radical-collaboration/extasy-bpti/blob/feature/entk-0.7/gmxcoco-bpti/gmxcoco.wcfg#L8) line) if you wanted to test the entire workflow for a small case.
> 
> I should be able to resolve the bug by end of day today.

I've tested this workaround with less compute units but still no luck!

I no longer get the connection error but the job still hangs between stage 2 and 3.

**Comment by vivek-bala** [comment]
Hey Chris, I am assuming you are able to reach the CoCo stage based on the messages from the slack channel. Same case here, the CoCo task seems to be either hang or take a long time to finish computation. I will let you take a look into that.

I was able to fix the original issue which you encountered with 20 CUs. Please try the [fix/extasy-bpti](https://github.com/radical-cybertools/radical.entk/tree/) branch of radical.entk. I have tested for the original case. The number of CUs should no longer be a factor.

Let me know how it goes!

**Comment by ChrisSuess** [comment]
Still seems to hang, new error posted below

```
2019-02-13 17:50:35,537: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Received heartbeat response
2019-02-13 17:50:35,537: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
2019-02-13 17:50:35,600: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Received heartbeat request
2019-02-13 17:50:35,601: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Sent heartbeat response
2019-02-13 17:50:35,727: radical.saga.pty    : umgr.0000.staging.output.0      : Thread-1       : DEBUG   : write: [  333] [   69] ( export PROMPT_COMMAND='' PS1='$' > /dev/null 2>&1 || set prompt='$'\n)
2019-02-13 17:50:35,727: radical.saga.pty    : umgr.0000.staging.output.0      : Thread-1       : DEBUG   : write: [  333] [   28] ( printf 'HELLO_%d_SAGA\n' 8\n)
2019-02-13 17:50:36,730: radical.saga.pty    : umgr.0000.staging.output.0      : Thread-1       : DEBUG   : write: [  333] [   69] ( export PROMPT_COMMAND='' PS1='$' > /dev/null 2>&1 || set prompt='$'\n)
2019-02-13 17:50:36,733: radical.saga.pty    : umgr.0000.staging.output.0      : Thread-1       : DEBUG   : write: [  333] [   28] ( printf 'HELLO_%d_SAGA\n' 9\n)
2019-02-13 17:50:37,736: radical.saga.pty    : umgr.0000.staging.output.0      : Thread-1       : DEBUG   : write: [  333] [   69] ( export PROMPT_COMMAND='' PS1='$' > /dev/null 2>&1 || set prompt='$'\n)
2019-02-13 17:50:37,737: radical.saga.pty    : umgr.0000.staging.output.0      : Thread-1       : DEBUG   : write: [  333] [   29] ( printf 'HELLO_%d_SAGA\n' 10\n)
2019-02-13 17:50:38,792: radical.saga.pty    : umgr.0000.staging.output.0      : Thread-1       : ERROR   : Could not detect shell prompt (timeout) (/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 290, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
2019-02-13 17:50:38,792: radical.saga.pty    : umgr.0000.staging.output.0      : Thread-1       : DEBUG   : Traceback (most recent call last):
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 290, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))

2019-02-13 17:50:38,792: radical.utils       : umgr.0000.staging.output.0      : Thread-1       : ERROR   : Could not create lease object
Traceback (most recent call last):
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/radical/utils/lease_manager.py", line 175, in _create_object
    obj = _LeaseObject (self, self._log, creator, args)
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/radical/utils/lease_manager.py", line 33, in __init__
    self.obj        = creator (*args)
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 284, in _shell_creator
    return sups.PTYShell(url, self.get_session(), self._logger)
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 248, in __init__
    self.pty_shell  = self.factory.run_shell  (self.pty_info)
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 450, in run_shell
    self._initialize_pty (sh_slave, info)
  File "/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 413, in _initialize_pty
    raise ptye.translate_exception (e)
NoSuccess: Could not detect shell prompt (timeout) (/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
2019-02-13 17:50:38,798: radical.entk.task_manager.0000: task-manager                    : umgr.0000.subscriber._state_sub_cb: DEBUG   : Unit unit.000079 in state FAILED
2019-02-13 17:50:38,799: radical.saga.pty    : umgr.0000.staging.output.0      : Thread-1       : DEBUG   : PTYProcess del  <saga.utils.pty_process.PTYProcess object at 0x7f6b93b07810>
2019-02-13 17:50:38,800: radical.saga.cpi    : umgr.0000.staging.output.0      : Thread-1       : DEBUG   : PTYShell del  <saga.utils.pty_shell.PTYShell object at 0x7f6b900a5310>
2019-02-13 17:50:38,802: radical.utils       : umgr.0000.staging.output.0      : Thread-1       : DEBUG   : lm create  object for gsisftp://bw.ncsa.illinois.edu/shell_file_adaptor_command_shell/
2019-02-13 17:50:38,805: radical.saga.cpi    : umgr.0000.staging.output.0      : Thread-1       : DEBUG   : PTYShell init <saga.utils.pty_shell.PTYShell object at 0x7f6b900664d0>
```

**Comment by vivek-bala** [comment]
```
NoSuccess: Could not detect shell prompt (timeout) (/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
```

This might be due to a ssh connectivity/stability issue. If I remember correctly, you are using a jetstream VM right? Do you get this error over multiple trials?

**Comment by ChrisSuess** [comment]
> ```
> NoSuccess: Could not detect shell prompt (timeout) (/home/ubuntu/shared/BW-COCO/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
> ```
> 
> This might be due to a ssh connectivity/stability issue. If I remember correctly, you are using a jetstream VM right? Do you get this error over multiple trials?

Im currently running it off a ubuntu instance using AWS. This is the first time ive seen this so will try again let you know if it appears again.

Did it work for you?

**Comment by vivek-bala** [comment]
Yea, if you are using the aws free tier, I wouldn't be surprised. I remember the ssh being unstable at times. I would recommend the jetstream VM.

> Did it work for you?

Yes, I ran it from my laptop to BW with up to 128 tasks in each stage. They all executed successfully. As mentioned before, the CoCo task hangs and that task does not complete. All previous tasks completed successfully.

**Comment by ChrisSuess** [comment]
We aren't using the free tier. Just run it again and got the same issue. Will try a complete fresh new instance.

**Comment by vivek-bala** [comment]
I see, okay. Good luck. Give the Jetstream VM a try as well, just to be sure.

**Comment by vivek-bala** [comment]
Hey Chris, just checking in. Let me know if you got a chance to give things a try.

**Comment by ChrisSuess** [comment]
Hi @vivek-bala, I have tried a couple more times using a variety of different local machines (Cloud and Physical) but still getting the same error message as of Wednesday. I have had success running Gromacs and CoCo workflows on BW by submitting with qsub.

**Comment by andre-merzky** [comment]
@ChrisSuess , can you please run again with `export RADICAL_SAGA_PTY_VERBOSE=DEBUG`, pack up all captured log output, and attach together with the local session sandbox?  Thanks!

**Comment by vivek-bala** [comment]
Hey Chris, any updates?

**Comment by ChrisSuess** [comment]
> @ChrisSuess , can you please run again with `export RADICAL_SAGA_PTY_VERBOSE=DEBUG`, pack up all captured log output, and attach together with the local session sandbox? Thanks!

So still no success in executing this successfully but I think we are now experiencing two problems.

1.  There is a temperamental connection issue. I have tried several different ways to consistently recreate the error submitting from different machines but can not pin point what the root of the problem is. Currently all jobs I run from a VM thats based in the U.S. have not encountered the connection issue, so this maybe a cause?

2. It appears that there is an issue with the staging within the workflow that is causing it to stall. I have had success running with a Gromacs and CoCo workflow.

I have run a new job using the `export RADICAL_SAGA_PTY_VERBOSE=DEBUG` setting as asked. I have attached a tarball of the entire directory for you to have a look at.

[bw_rp_errors.tar.gz](https://github.com/radical-collaboration/extasy-bpti/files/2881838/bw_rp_errors.tar.gz)

**Comment by mturilli** [comment]
Hi @ChrisSuess, for problem 1., if running from a VM on the US is a problem, we can offer support with one of our dedicated VM. We did encounter connection resets from the UK before with another project so I think it would be safe to assume running your workflows only from VMs in the US. This is a problem with Blue Waters so, unfortunately, we do not have control over it.

**Comment by vivek-bala** [comment]
Thanks Chris. It looks like you are able to execute all tasks except the CoCo task. The following is the last entry I see before a keyboard interrupt:
```
2019-02-19 17:50:17,793: radical.entk.task_manager.0000: task-manager                    : umgr.0000.idler._state_pull_cb: DEBUG   : Unit unit.000080 in state AGENT_EXECUTING
```

This is exactly what I faced as well. I believe the CoCo task does not finish executing. Can you take a look inside unit.000080 inside radical pilot sandbox on Blue Waters? You can share the specific path with me as well. I can help to check if the data staging is correct or no. You can take a look whether pyCoCo executes as expected.

**Comment by ChrisSuess** [comment]
In the `runme.py` i have noticed that it's linking to @vivek-bala installations of Gromacs and CoCo which are pretty dated. 

https://github.com/radical-collaboration/extasy-bpti/blob/f9e4a5acf0291bc07e71719913916fd59cccd67c/gmxcoco-bpti/runme.py#L583

https://github.com/radical-collaboration/extasy-bpti/blob/f9e4a5acf0291bc07e71719913916fd59cccd67c/gmxcoco-bpti/runme.py#L593

https://github.com/radical-collaboration/extasy-bpti/blob/f9e4a5acf0291bc07e71719913916fd59cccd67c/gmxcoco-bpti/runme.py#L610-L613

This might be a cause for the workflow failing at the CoCo stage. I have updated this to link to my own installations which should hopefully play nicer together. (Still waiting in the BW queue!)
